spring.application.name=authentication-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/nutritionix
spring.datasource.username=postgres
spring.datasource.password=502291
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

bootstrap-server=localhost:9092