spring:
  application:
    name: user-service

  cloud:
    consul:
      discovery:
        service-name: user-service
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
