spring.application.name=user-service

server.port=8081
spring.profiles.active=dev


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=health