spring.application.name=liquibase

spring.liquibase.enabled=true
management.endpoints.web.exposure.include=metrics
management.endpoint.metrics.access=unrestricted
management.endpoint.health.show-details=always
management.tracing.enabled=true

spring.profiles.active=dev
server.port=8001

logging.level.liquibase=WARN