spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/users${segment}

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/?.*), /api/auth${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info
